package com.example.business;

import java.io.Serializable;

public class Nota implements Serializable {
	private static final long serialVersionUID = 1L; //generated by IDE
	private String title;
	private String body;
	
	public Nota(String title, String body) {
		this.title = title;
		this.body = body;
	}
	
	public void setBody(String body) {
		this.body = body;
	}
	
	public void setTitle(String title) {
		this.title = title;
	}
	
	public String getBody() {
		return body;
	}
	
	public String getTitle() {
		return title;
	}
	
	@Override
	public String toString() {
		return title;
	}
}
